require("core.general")
require("core.keymaps")

require("plugins")

require("_illuminate")
require("_gruvbox")
require("_nvim-tree")
require("_lualine")
require("_neoscroll")
require("_gitsigns")
require("_nvim-lsp-installer")
require("_nvim-lspconfig")
require("_nvim-cmp")
require("_nvim-treesitter")
require("_telescope")
require("_nvim-autopairs")
require("_nvim-treesitter-context")
require("_which-key")
require("_dashboard-nvim")
require("_nvim-dap-ui")

-- 
vim.cmd("hi IlluminatedWordRead guibg=#525252 gui=none")
vim.cmd("hi IlluminatedWordText  guibg=#525252 gui=none")
vim.cmd("hi IlluminatedWordWrite guibg=#525252 gui=none")
