vim.g.mapleader = ' ';
vim.api.nvim_set_option('number', true)
vim.api.nvim_set_option('relativenumber', true)
vim.api.nvim_set_option('tabstop', 2)
vim.api.nvim_set_option('shiftwidth', 2)
vim.api.nvim_set_option('expandtab', true)
vim.api.nvim_set_option('smarttab', true)
vim.api.nvim_set_option('autoindent', true)
vim.api.nvim_set_option('showtabline', 2)
vim.api.nvim_set_option('cursorline', true)
